<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ashley Dosch, Amy Muller, Anthony Stawiery">
<meta name="dcterms.date" content="2023-07-29">

<title>Generalized Estimating Equations</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Generalized Estimating Equations</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ashley Dosch, Amy Muller, Anthony Stawiery </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 29, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Generalized Estimating Equations (GEE) is a statistical methodology in a class of models that model the mean of an outcome as function of predictor variables commonly used to analyze correlated data in various fields that use panel or longitudinal data, including epidemiology, social sciences, and clinical trials <span class="citation" data-cites="Mcculloch2008">(<a href="#ref-Mcculloch2008" role="doc-biblioref">S. McCulloch C. 2008</a>)</span>. The method was first introduced by Liang and Zeger in a paper in 1986. <span class="citation" data-cites="Liang1986longitudinal">(<a href="#ref-Liang1986longitudinal" role="doc-biblioref">Liang and Zeger 1986</a>)</span>. The method uses a quasilikelihood approach and yields population averaged estimates of parameters. <span class="citation" data-cites="wang2014generalized">(<a href="#ref-wang2014generalized" role="doc-biblioref">M. Wang 2014</a>)</span></p>
<p>Analysis of longitudinal data has inherent problems with independence involving multiple observations for the same individual in clinical data studies. Liang and Zeger even referred to time dependence on multiple observations of an individual as a nuisance due to correlation issues. <span class="citation" data-cites="Liang1986longitudinal">(<a href="#ref-Liang1986longitudinal" role="doc-biblioref">Liang and Zeger 1986</a>)</span>. Another challenge for use of longitudinal data is the need for more complex statistical models to deal with the lack of independence in observations that could include multidimensional levels of integration, and the software is often not available.<span class="citation" data-cites="donald2006longitudinal">(<a href="#ref-donald2006longitudinal" role="doc-biblioref">Donald and Robert 2006</a>)</span> The use of GEE mitigates these challenges with use of longitudinal data.</p>
<p>GEE extends the generalized linear model framework to account for within-cluster correlations, such as repeated observations or clustered data. <span class="citation" data-cites="shao2023comparison">(<a href="#ref-shao2023comparison" role="doc-biblioref">Shao et al. 2023</a>)</span> GEE is used to model the marginal mean response while allowing for flexible correlation structures among observations within the same group or cluster. GEE estimates population-average effects by specifying a working correlation structure such as independence or exchangeable structures.<span class="citation" data-cites="shao2023comparison">(<a href="#ref-shao2023comparison" role="doc-biblioref">Shao et al. 2023</a>)</span> GEE also implements an estimating equation approach to iteratively update the parameter estimates.</p>
<p>This methodology provides reliable and robust estimates, even when the correlation structure is mis-specified.<span class="citation" data-cites="wang2014generalized">(<a href="#ref-wang2014generalized" role="doc-biblioref">M. Wang 2014</a>)</span> GEE is particularly useful for longitudinal or panel data analysis, as it allows for examination of all available data in the experiment and provides statistical inference for population-level ramifications. <span class="citation" data-cites="lin2011impact">(<a href="#ref-lin2011impact" role="doc-biblioref">Lin and Perng 2011</a>)</span> Its ability to handle missing data makes GEE a great choice for analyzing correlated data, particularly in biostatistics or research settings without the use of intense statistical mathematics.</p>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<section id="estimating-equations" class="level3">
<h3 class="anchored" data-anchor-id="estimating-equations">Estimating Equations</h3>
<p>Instead of maximizing the likelihood function, GEE employs a quasilikelihood estimating equation approach to estimate the regression parameters.<span class="citation" data-cites="d2011generalized">(<a href="#ref-d2011generalized" role="doc-biblioref">D’Angelo et al. 2011</a>)</span> The estimating equations are derived based on the assumed correlation structure and the marginal mean model,not a specified distriution. <span class="citation" data-cites="d2011generalized">(<a href="#ref-d2011generalized" role="doc-biblioref">D’Angelo et al. 2011</a>)</span> GEE models can be for continuous, binary or count outcomes.</p>
</section>
<section id="iterative-algorithm" class="level3">
<h3 class="anchored" data-anchor-id="iterative-algorithm">Iterative Algorithm</h3>
<p>GEE uses an iterative algorithm after using initial estimates for regression coefficients, <span class="math inline">\(\beta_i\)</span>, to update the parameter estimates. Software packages, such as ‘geepack’ package in R handle the iteration process. The iterative process works until there is convergence to stable estimates. <span class="citation" data-cites="Hojsgaard2006">(<a href="#ref-Hojsgaard2006" role="doc-biblioref">Halekoh, Højsgaard, and Yan 2006</a>)</span> <span class="citation" data-cites="Liang1986longitudinal">(<a href="#ref-Liang1986longitudinal" role="doc-biblioref">Liang and Zeger 1986</a>)</span></p>
</section>
<section id="data-structure" class="level3">
<h3 class="anchored" data-anchor-id="data-structure">Data Structure</h3>
<p>GEE is designed for analyzing correlated data, such as longitudinal or panel data in which the data is organized into clusters, where each cluster represents a group of related observations.<span class="citation" data-cites="Mcculloch2008">(<a href="#ref-Mcculloch2008" role="doc-biblioref">S. McCulloch C. 2008</a>)</span> The assumption of independent observations may not be accurate. A GEE analysis of a dataset with longitudinal data with repeated observations per individual will be shown using the respiratory dataset available through the ‘geepack’ package in R.</p>
</section>
<section id="model-specification" class="level3">
<h3 class="anchored" data-anchor-id="model-specification">Model Specification</h3>
<p>GEE is an extension of generalized linear models (GLM) and uses that framework to specify the relationship between the response variable and the regressor variables. <span class="citation" data-cites="shao2023comparison">(<a href="#ref-shao2023comparison" role="doc-biblioref">Shao et al. 2023</a>)</span> The choice of the link function and the distribution of the response variable depends on the nature of the data.<span class="citation" data-cites="gayen2018generalized">(<a href="#ref-gayen2018generalized" role="doc-biblioref">Gayen and Kumar 2018</a>)</span> Models can be created for continuous, binary or count outcomes. The table below shows the extension of GEE from the LM, GLM,and GLMM and differences in assumptions.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Model_Comparison_Table.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure 1: Model Comparision and Summary <span class="citation" data-cites="Mcculloch2008">(<a href="#ref-Mcculloch2008" role="doc-biblioref">S. McCulloch C. 2008</a>)</span></figcaption>
</figure>
</div>
<p>According the Liang and Zeger, the method of GEE, longitudinal data sets, are comprised of an outcome variable, <span class="math inline">\(y_{it}\)</span>, and $$p\times1$$ vector of covariates, <span class="math inline">\(x_{it}\)</span>, observed at times <span class="math display">\[t=1,...,n_{it}\]</span> for subjects <span class="math display">\[i=1,...,K\]</span> which arise often in applied sciences. <span class="citation" data-cites="Liang1986longitudinal">(<a href="#ref-Liang1986longitudinal" role="doc-biblioref">Liang and Zeger 1986</a>)</span> For example, in health care study data, individual patients have follow visits to monitor a treatment plan and therefore have multiple observations for each patient. GEE is used for these kind of longitudinal datasets due to the use of correlation structures in its modeling design to account for the lack of independence in the repeated observations.</p>
<p>In Wang’s review of GEE method, a marginal model specifying a relationship between <span class="math inline">\(\mu_i\)</span> and <span class="math inline">\(X_{ij}\)</span> is given by the equation <span class="math inline">\(g(\mu_{ij})=X'_{ij} \beta\)</span>, where <span class="math inline">\(g\)</span> is the link function and <span class="math inline">\(\beta\)</span> is a vector of regression coefficients and then shows the mathematical calculations to get to the equation</p>
<p><span class="math inline">\(U(\beta) = \sum_{i=1}^K {D_i}^{\prime} {V_i}^{-1}(Y_i-\mu_i)=0\)</span></p>
<p>that when solved will give estimates of <span class="math inline">\(\beta_i\)</span> used in the generated models. In this equation <span class="math inline">\(D_i=\partial\mu_i/\partial\beta^{\prime}\)</span> and <span class="math inline">\({V_i}^{-1}\)</span> is the inverse of the variance-covariance matrix for <span class="math inline">\(Y_i\)</span>, <span class="math inline">\(V_i = \phi{A_i}^{1/2}R_i(\)</span><span class="math inline">\(){A_i}^{1/2}\)</span> , <span class="math inline">\(A_i\)</span> is a diagonal matrix with elements that are known variance functions of <span class="math inline">\(\mu_{ij}\)</span> times a scaling parameter <span class="math inline">\(\phi\)</span>, and <span class="math inline">\(R_i(\)</span><span class="math inline">\()\)</span> is the correlation structure. <span class="citation" data-cites="wang2014generalized">(<a href="#ref-wang2014generalized" role="doc-biblioref">M. Wang 2014</a>)</span></p>
<p>GEE employ a logistic regression model created using the ‘geepack’ package available in R, specifying a correlation structure (see the structure types in the paragraph below), family type of binomial for discrete outcomes and would yield model of</p>
<p>General mathematical formula for multivariate GEE using the logit link function for binary outcomes: <span class="math display">\[
\text{logit}[P(y_\text{ij}=1)]=log\left(\dfrac{\pi_{ij}}{1-\pi_{ij}}\right)=\beta_0+Regressor1_{ij}\beta_1+Regressor2_{ij}\beta_2...+RegressorN\beta_{N-1}
\]</span></p>
<p>that predicts log odds ratios for outcomes for each predictor. <span class="citation" data-cites="PSU2023">(<a href="#ref-PSU2023" role="doc-biblioref">Statistics 2023</a>)</span></p>
<p>The ‘geepack’ package in R uses the link and variance functions in the geeglm() function of identity for gaussian, logit and <span class="math inline">\(\mu(1-\mu),\mu\in(0,1)\)</span> for binomal, log and<span class="math inline">\(\mu,\mu&gt;0\)</span> for poisson, and log and <span class="math inline">\(\mu^2,\mu&gt;0\)</span> for gamma families. <span class="citation" data-cites="Hojsgaard2006">(<a href="#ref-Hojsgaard2006" role="doc-biblioref">Halekoh, Højsgaard, and Yan 2006</a>)</span></p>
</section>
<section id="correlation-structures" class="level3">
<h3 class="anchored" data-anchor-id="correlation-structures">Correlation Structures</h3>
<p>GEE allows for flexible modeling of the correlation structure within clusters. A working correlation structure is specified, which represents the assumed relationship among the correlated observations <span class="citation" data-cites="seals2016analysis">(<a href="#ref-seals2016analysis" role="doc-biblioref">Seals and Aban 2016</a>)</span>. The correlation structures discussed in this paper are exchangeable, autoregressive (AR1), unstructured, and independent.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="corr-table.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure 2: Correlation Structures Comparison Table <span class="citation" data-cites="wang2014generalized">(<a href="#ref-wang2014generalized" role="doc-biblioref">M. Wang 2014</a>)</span></figcaption>
</figure>
</div>
<p>The independent correlation structure is used when the assumption between multiple repeated observations of a single individual is independent. Use of the exchange correlation structure is used when there is equality between times of observations. Autoagressive (AR1) correlation structure is used when there are more than one set of equal time differences between repeated observations. And lastly, unstructured correlation structure is the most general and takes into account all the possible time intervals between repeated observations. Of course there are more choices for correlation structures, but these (4) structures are the structures used in the ‘geepack’ R package used in the subsequent examples.</p>
<p>If the correlation structure chosen for GEE is not correct, the predictor variables will still be estimated consistently, since the GEE method relies on the first moment, however the standard errors will be incorrect. This considered very attractive property of GEE models.<span class="citation" data-cites="donald2006longitudinal">(<a href="#ref-donald2006longitudinal" role="doc-biblioref">Donald and Robert 2006</a>)</span> A possible remedy for choosing a correlation structure incorrectly is to use the ‘sandwich’ package in R that uses the Huber-White sandwich estimator to create an an approximation for the correlation.<span class="citation" data-cites="homish2010analyzing">(<a href="#ref-homish2010analyzing" role="doc-biblioref">Homish et al. 2010</a>)</span> <span class="citation" data-cites="zeileis2019package">(<a href="#ref-zeileis2019package" role="doc-biblioref">Zeileis et al. 2019</a>)</span> By default, the ‘geepack’ package in R uses a sandwich estimator if the number of clusters is larger than 30, but has a built in options to use another variance estimator called the jackknife estimator, fully iterated or approximate, for cases where the number of clusters is less than 30 (as recommended by <span class="citation" data-cites="paik1988repeated">(<a href="#ref-paik1988repeated" role="doc-biblioref">Paik 1988</a>)</span>).<span class="citation" data-cites="Hojsgaard2006">(<a href="#ref-Hojsgaard2006" role="doc-biblioref">Halekoh, Højsgaard, and Yan 2006</a>)</span></p>
<p>Correlation structure selection is determined through various methods and is not limited to the structures shown in the correlation table above. One valid method used to determine model selection has been proposed by Shults and Chaganty <span class="citation" data-cites="wang2012penalized">(<a href="#ref-wang2012penalized" role="doc-biblioref">L. Wang, Zhou, and Qu 2012</a>)</span> as to determine the structure based on the generalized error sum of squares given by the following equation: <span class="math display">\[
  ESS(\alpha,\beta) = \sum_{i=1}^{K}{(Y_i - \mu _i)}'{V_{i}}^{-1}(Y_i - \mu _i)
\]</span> In addition to the method by Schuts and Chaganty, Wang discusses several other methods for correlation structure selection and cites many other methods available. <span class="citation" data-cites="wang2014generalized">(<a href="#ref-wang2014generalized" role="doc-biblioref">M. Wang 2014</a>)</span></p>
</section>
</section>
<section id="analysis-and-results" class="level2">
<h2 class="anchored" data-anchor-id="analysis-and-results">Analysis and Results</h2>
<section id="data-and-visualisation" class="level3">
<h3 class="anchored" data-anchor-id="data-and-visualisation">Data and Visualisation</h3>
<p>In this review of GEE, the ‘geepack’ package for R with a respiratory dataset included was used to showcase an example. <span class="citation" data-cites="Hojsgaard2006">(<a href="#ref-Hojsgaard2006" role="doc-biblioref">Halekoh, Højsgaard, and Yan 2006</a>)</span> <span class="citation" data-cites="Yan2004">(<a href="#ref-Yan2004" role="doc-biblioref">Yan and Fine 2004</a>)</span> <span class="citation" data-cites="Yan2002">(<a href="#ref-Yan2002" role="doc-biblioref">Yan 2002</a>)</span> The respiratory dataset included in the packet is an example of longitudinal or panel data as data is from a clinical study of 111 patients receiving treatment for a respiratory illness. <span class="citation" data-cites="koch1990categorical">(<a href="#ref-koch1990categorical" role="doc-biblioref">Koch et al. 1990</a>)</span></p>
<table class="table">
<caption>Figure 3: Respiratory Variable Summary</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>center</td>
<td>a numeric vector</td>
</tr>
<tr class="even">
<td>id</td>
<td>a numeric vector</td>
</tr>
<tr class="odd">
<td>treat</td>
<td>treatment or placebo</td>
</tr>
<tr class="even">
<td>sex</td>
<td>male or female</td>
</tr>
<tr class="odd">
<td>age</td>
<td>in years at baseline</td>
</tr>
<tr class="even">
<td>baseline</td>
<td>respiratory status at baseline</td>
</tr>
<tr class="odd">
<td>visit</td>
<td>id of visit</td>
</tr>
<tr class="even">
<td>outcome</td>
<td>respiratory status at visit</td>
</tr>
</tbody>
</table>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">######## loading packages ########</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geepack)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)   <span class="co"># For fitting linear mixed models</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmTMB)  <span class="co"># For fitting GLMMs with different distributions</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(furniture)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="do">######## Load Data ########</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(respiratory)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>displayData <span class="ot">&lt;-</span> respiratory[respiratory<span class="sc">$</span>id <span class="sc">&lt;</span> <span class="dv">4</span>,]</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>displayData <span class="ot">&lt;-</span> displayData[displayData<span class="sc">$</span>center <span class="sc">==</span> <span class="dv">2</span>,]</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="do">######## Plot sample of data for visualization ########</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(displayData, <span class="fu">aes</span>(<span class="at">x=</span>visit, <span class="at">y=</span>treat, <span class="at">color=</span><span class="fu">factor</span>(outcome))) <span class="sc">+</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>)) <span class="sc">+</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="st">"Respiratory Health"</span>,<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Poor"</span>,<span class="st">"Good"</span>)) <span class="sc">+</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(.<span class="sc">~</span>id) <span class="sc">+</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Visit Number/Patient"</span>, <span class="at">y =</span> <span class="st">"Treatent, 'A' = Treatment, 'P' = Placebo"</span>,<span class="at">title =</span> <span class="st">"Figure 4: Respiratory Treatment Outcomes Over (4) Patient Visits"</span>)<span class="sc">+</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Figure 4, the above graphic, is displaying a small sample from the ‘respiratory’ data. The given data set is a study with longitudinal data of repeated measures with a binary outcome. There are four measures, or visits, performed on each individual. Each box with 1 through 4 on the x-axis represents a unique patient and their respective visits. The y-axis displays the treatment the patient is taking where P represents a placebo and A represents the actual treatment.</p>
<p>The points on the plot indicate the outcome of treatment and represent a patient’s respiratory status per visit where 1 indicates a “good” respiratory status and 0 indicates a “poor” respiratory status. Note that this graphic is a truncated form of the complete dataset and excludes both a treatment center and 52 other patients.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">###### Data transformation for "wide" data [record per visit] #######</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>resp_transformed <span class="ot">&lt;-</span> respiratory <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">spread</span>(<span class="at">key =</span> visit,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">value =</span> outcome,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">sep =</span> <span class="st">"_"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(id) <span class="sc">%&gt;%</span> </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(id, center, </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>                sex, age, treat, </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>                baseline, <span class="fu">starts_with</span>(<span class="st">"visit"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>‘resp_transformed’ is a data frame that has been transformed based on the original data set. This transformation manipulates the data such that there is one line per participant in the data. This method will allow for analyzing the metrics between repeated observations.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">###### Table of data breakdown - respiratory outcome over time #######</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>resp_transformed <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(treat) <span class="sc">%&gt;%</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  furniture<span class="sc">::</span><span class="fu">table1</span>(<span class="st">"Visit One"</span> <span class="ot">=</span> visit_1, </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Visit Two"</span> <span class="ot">=</span> visit_2, </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Visit Three"</span> <span class="ot">=</span> visit_3, </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Visit Four"</span> <span class="ot">=</span> visit_4, </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">caption =</span> <span class="st">"Figure 5: Respiratory Outcome Over Time"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">output =</span> <span class="st">"markdown"</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">na.rm =</span> <span class="cn">FALSE</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                    <span class="at">total =</span> <span class="cn">TRUE</span>,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">test =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Figure 5: Respiratory Outcome Over Time</caption>
<thead>
<tr class="header">
<th></th>
<th>Total</th>
<th>A</th>
<th>P</th>
<th>P-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>n = 111</td>
<td>n = 54</td>
<td>n = 57</td>
<td></td>
</tr>
<tr class="even">
<td>Visit One</td>
<td></td>
<td></td>
<td></td>
<td>0.038</td>
</tr>
<tr class="odd">
<td></td>
<td>0.6 (0.5)</td>
<td>0.7 (0.5)</td>
<td>0.5 (0.5)</td>
<td></td>
</tr>
<tr class="even">
<td>Visit Two</td>
<td></td>
<td></td>
<td></td>
<td>&lt;.001</td>
</tr>
<tr class="odd">
<td></td>
<td>0.5 (0.5)</td>
<td>0.7 (0.5)</td>
<td>0.4 (0.5)</td>
<td></td>
</tr>
<tr class="even">
<td>Visit Three</td>
<td></td>
<td></td>
<td></td>
<td>0.004</td>
</tr>
<tr class="odd">
<td></td>
<td>0.6 (0.5)</td>
<td>0.7 (0.5)</td>
<td>0.5 (0.5)</td>
<td></td>
</tr>
<tr class="even">
<td>Visit Four</td>
<td></td>
<td></td>
<td></td>
<td>0.07</td>
</tr>
<tr class="odd">
<td></td>
<td>0.5 (0.5)</td>
<td>0.6 (0.5)</td>
<td>0.4 (0.5)</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Figure 5 “Respiratory Outcome Over Time” shows a breakdown of visits and the corresponding statistics. N is the total number of patients in the study, “A” represents the treatment, and “P” represents the placebo.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="do">###### Graph of Number of Visits with Poor Outcome #######</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>resp_transformed <span class="sc">%&gt;%</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">n_good =</span> furniture<span class="sc">::</span><span class="fu">rowsums</span>(visit_1 <span class="sc">==</span> <span class="st">"0"</span>, </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                                            visit_2 <span class="sc">==</span> <span class="st">"0"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                                            visit_3 <span class="sc">==</span> <span class="st">"0"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                                            visit_4 <span class="sc">==</span> <span class="st">"0"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> n_good)) <span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_count</span>() <span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age in Years"</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Visits out of Four, with 'Poor' Respiration"</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Figure 6: 'Poor' Respiration Outcomes for Total Visits"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This visualization is focused on the age parameter in terms of outcome per visit. Based on age for the x-axis, it’s displaying whether respective patients had a ‘poor’ outcome (or poor respiration status) as a number out of the four total visits. The larger circles indicate a higher number of poor outcomes in total, while the smaller circles indicate a smaller number of poor outcomes in total. This visual does not display patients who had all ‘good’ outcomes.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">###### Correlation between repeated observations #######</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>resp_transformed <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">"visit"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate_all</span>(<span class="cf">function</span>(x) x <span class="sc">==</span> <span class="st">"1"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  corrplot<span class="sc">::</span><span class="fu">corrplot</span>(<span class="at">title =</span> <span class="st">"Figure 7: Correlation Matrix for Repeated Visits"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">mar=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The preceding graphic, figure 7, shows the correlation matrix between repeated observations. It’s noted that there is a medium to high correlation between the observations. This is showing the necessity for a statistical model that can account for these levels of correlation between the observations.</p>
</section>
<section id="statistical-modeling" class="level3">
<h3 class="anchored" data-anchor-id="statistical-modeling">Statistical Modeling</h3>
<section id="gee-models" class="level4">
<h4 class="anchored" data-anchor-id="gee-models">GEE Model(s)</h4>
<p>GEE models focus on the mean of the correlated observations that are within groups and don’t focus on the distribution of the full data of the population <span class="citation" data-cites="Hojsgaard2006">(<a href="#ref-Hojsgaard2006" role="doc-biblioref">Halekoh, Højsgaard, and Yan 2006</a>)</span>. GEE modeling requires parameters in the form of distribution of the response variable, the link function, the regressor variables, and the desired correlation structure. The various types of correlation structures were discussed in the previous methodology section; our example focuses on independent, exchangeable, unstructured, and auto-regressive order 1 correlation structures. The distribution selected for a model is based on the distribution of the response variable <span class="citation" data-cites="seals2016analysis">(<a href="#ref-seals2016analysis" role="doc-biblioref">Seals and Aban 2016</a>)</span> and may be a value such as binomial, Poisson, or Gaussian <span class="citation" data-cites="gayen2018generalized">(<a href="#ref-gayen2018generalized" role="doc-biblioref">Gayen and Kumar 2018</a>)</span>. The link function parameter is contingent on the corresponding distribution where the distribution of the response variable dictates the model to be used <span class="citation" data-cites="agresti2015foundations">(<a href="#ref-agresti2015foundations" role="doc-biblioref">Agresti 2015</a>)</span>.</p>
<p>The ‘geepack’ package in R was used to create four different models using the same geeglm() function and specifying different correlation structures as parameters within the function input. The binomial distribution is chosen for each model as well due to the binary response of a ‘poor’ or ‘good’ respiratory status. The canonical link function used for binary response data is ‘logit’ or logistic regression <span class="citation" data-cites="agresti2015foundations">(<a href="#ref-agresti2015foundations" role="doc-biblioref">Agresti 2015</a>)</span>. This link function is inherently used in our models without direct specification.</p>
<ol type="1">
<li><strong>GEE with Independent Correlation Structure</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># GEE with independent correlation structure</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>gee_independence <span class="ot">&lt;-</span> <span class="fu">geeglm</span>(outcome <span class="sc">~</span> center <span class="sc">+</span> treat <span class="sc">+</span> age <span class="sc">+</span> baseline <span class="sc">+</span> sex, <span class="at">data=</span>respiratory, <span class="at">id=</span>id, </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> <span class="fu">binomial</span>(), <span class="at">corstr=</span><span class="st">"independence"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gee_independence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
geeglm(formula = outcome ~ center + treat + age + baseline + 
    sex, family = binomial(), data = respiratory, id = id, corstr = "independence")

 Coefficients:
            Estimate  Std.err   Wald Pr(&gt;|W|)    
(Intercept) -0.10346  0.88213  0.014 0.906634    
center       0.64949  0.35322  3.381 0.065952 .  
treatP      -1.26536  0.34668 13.322 0.000262 ***
age         -0.01876  0.01296  2.093 0.147974    
baseline     1.84572  0.34598 28.460 9.57e-08 ***
sexM        -0.13678  0.44025  0.097 0.756035    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation structure = independence 
Estimated Scale Parameters:

            Estimate Std.err
(Intercept)    1.002  0.1842
Number of clusters:   111  Maximum cluster size: 4 </code></pre>
</div>
</div>
<p>The GEE model summary with an independent correlation structure specified shows that there are no estimated correlation parameters. Referencing back to Figure 2, it’s noted that the estimator column for an independent correlation structure is empty. This is because the independent correlation structure is assuming there is no correlation between the observations within a cluster <span class="citation" data-cites="seals2016analysis">(<a href="#ref-seals2016analysis" role="doc-biblioref">Seals and Aban 2016</a>)</span>.</p>
<ol start="2" type="1">
<li><strong>GEE with Exchangeable Correlation Structure</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># GEE with exchangeable correlation structure</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>gee_exchangeable <span class="ot">&lt;-</span> <span class="fu">geeglm</span>(outcome <span class="sc">~</span> center <span class="sc">+</span> treat <span class="sc">+</span> age <span class="sc">+</span> baseline <span class="sc">+</span> sex, <span class="at">data=</span>respiratory, <span class="at">id=</span>id, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> <span class="fu">binomial</span>(), <span class="at">corstr=</span><span class="st">"exchangeable"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gee_exchangeable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
geeglm(formula = outcome ~ center + treat + age + baseline + 
    sex, family = binomial(), data = respiratory, id = id, corstr = "exchangeable")

 Coefficients:
            Estimate Std.err  Wald Pr(&gt;|W|)    
(Intercept)  -0.1035  0.8821  0.01  0.90663    
center        0.6495  0.3532  3.38  0.06595 .  
treatP       -1.2654  0.3467 13.32  0.00026 ***
age          -0.0188  0.0130  2.09  0.14797    
baseline      1.8457  0.3460 28.46  9.6e-08 ***
sexM         -0.1368  0.4402  0.10  0.75604    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation structure = exchangeable 
Estimated Scale Parameters:

            Estimate Std.err
(Intercept)        1   0.184
  Link = identity 

Estimated Correlation Parameters:
      Estimate Std.err
alpha    0.329  0.0838
Number of clusters:   111  Maximum cluster size: 4 </code></pre>
</div>
</div>
<p>The GEE model summary with an exchangeable correlation structure specified shows that there is one estimated correlation parameter. One again referencing back to Figure 2, it’s noted that the estimator parameter (<span class="math inline">\(\alpha\)</span>) is contained in the working correlation structure. The <span class="math inline">\(\alpha\)</span> value in the summary shows that there is an estimated 0.329 correlation value between visits for patients, or a 0.329 correlation value between observations in a cluster.</p>
<ol start="3" type="1">
<li><strong>GEE with Unstructured Correlation Structure</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># GEE with unstructured correlation structure</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>gee_unstructured <span class="ot">&lt;-</span> <span class="fu">geeglm</span>(outcome <span class="sc">~</span> center <span class="sc">+</span> treat <span class="sc">+</span> age <span class="sc">+</span> baseline <span class="sc">+</span> sex, <span class="at">data=</span>respiratory, <span class="at">id=</span>id, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> <span class="fu">binomial</span>(), <span class="at">corstr=</span><span class="st">"unstructured"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gee_unstructured)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
geeglm(formula = outcome ~ center + treat + age + baseline + 
    sex, family = binomial(), data = respiratory, id = id, corstr = "unstructured")

 Coefficients:
            Estimate Std.err  Wald Pr(&gt;|W|)    
(Intercept)  -0.1826  0.8685  0.04  0.83351    
center        0.6555  0.3513  3.48  0.06203 .  
treatP       -1.2455  0.3455 12.99  0.00031 ***
age          -0.0176  0.0129  1.87  0.17147    
baseline      1.8944  0.3441 30.31  3.7e-08 ***
sexM         -0.1144  0.4407  0.07  0.79528    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation structure = unstructured 
Estimated Scale Parameters:

            Estimate Std.err
(Intercept)     1.01   0.194
  Link = identity 

Estimated Correlation Parameters:
          Estimate Std.err
alpha.1:2    0.321   0.118
alpha.1:3    0.206   0.101
alpha.1:4    0.284   0.110
alpha.2:3    0.424   0.141
alpha.2:4    0.343   0.119
alpha.3:4    0.380   0.133
Number of clusters:   111  Maximum cluster size: 4 </code></pre>
</div>
</div>
<p>The GEE model summary with an unstructured correlation structure specified shows that there are six individual estimated correlation parameters for the between observation correlation. Figure 2 shows that the <span class="math inline">\(\alpha\)</span> values in an unstructured correlation structure is a set of the pairwise estimated correlation parameter values. The <span class="math inline">\(\alpha\)</span> values correspond to a specific location within the working correlation matrix.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>gee_unstructured<span class="sc">$</span>geese<span class="sc">$</span>alpha</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>alpha.1:2 alpha.1:3 alpha.1:4 alpha.2:3 alpha.2:4 alpha.3:4 
    0.321     0.206     0.284     0.424     0.343     0.380 </code></pre>
</div>
</div>
<p>For this model summary, the <span class="math inline">\(\alpha\)</span> values above demonstrate the estimated correlation value between observations, where the ‘alpha.1:2’ value of 0.321 equates to the correlation value between observations of visit 1 and visit 2.</p>
<ol start="4" type="1">
<li><strong>GEE with Auto-Regressive Order 1 Correlation Structure</strong></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># GEE with Auto-Regressive Order 1 correlation structure</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>gee_ar1 <span class="ot">&lt;-</span> <span class="fu">geeglm</span>(outcome <span class="sc">~</span> center <span class="sc">+</span> treat <span class="sc">+</span> age <span class="sc">+</span> baseline <span class="sc">+</span> sex, <span class="at">data=</span>respiratory, <span class="at">id=</span>id, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> <span class="fu">binomial</span>(), <span class="at">corstr=</span><span class="st">"ar1"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gee_ar1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
geeglm(formula = outcome ~ center + treat + age + baseline + 
    sex, family = binomial(), data = respiratory, id = id, corstr = "ar1")

 Coefficients:
            Estimate Std.err  Wald Pr(&gt;|W|)    
(Intercept)  -0.3231  0.8716  0.14  0.71083    
center        0.7297  0.3525  4.29  0.03843 *  
treatP       -1.1914  0.3483 11.70  0.00062 ***
age          -0.0174  0.0129  1.83  0.17647    
baseline      1.8709  0.3466 29.14  6.7e-08 ***
sexM         -0.1346  0.4477  0.09  0.76365    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation structure = ar1 
Estimated Scale Parameters:

            Estimate Std.err
(Intercept)     1.01    0.19
  Link = identity 

Estimated Correlation Parameters:
      Estimate Std.err
alpha    0.457  0.0896
Number of clusters:   111  Maximum cluster size: 4 </code></pre>
</div>
</div>
<p>The GEE model summary with an autoregressive (AR1) correlation structure specified shows that there is one estimated correlation parameter for the between observation correlation. Figure 2 shows that the <span class="math inline">\(\alpha\)</span> values in an AR1 correlation structure is two values where one value is <span class="math inline">\(\alpha\)</span> and the other value is <span class="math inline">\(\alpha{2}\)</span>. The <span class="math inline">\(\alpha\)</span> values once again correspond to a specific location within the working correlation matrix.</p>
</section>
</section>
<section id="model-assessment" class="level3">
<h3 class="anchored" data-anchor-id="model-assessment">Model Assessment</h3>
<p>After fitting the GEE model, various model diagnostics can be performed to assess the model’s goodness of fit, such as model comparison criteria and assessing the adequacy of the assumed correlation structure. <span class="citation" data-cites="shao2023comparison">(<a href="#ref-shao2023comparison" role="doc-biblioref">Shao et al. 2023</a>)</span></p>
<p>The following formula is the logistic regression model unique to the respiratory data set. This formula was translated into the four different models above with a different correlation structure specified per model. Using the variables center, treatment, age, baseline, and sex, the model is attempting to determine how these variables affect the likelihood of a ‘poor’ outcome versus a ‘good’ outcome within a patient’s visit. Note that all model analyses are completed on the full model and we have taken no actions to reduce the models, whether through stepwise fashion or other methods. There was no determination to remove statistically insignificant regressor variables.</p>
<p><span class="math display">\[
\log\left(\dfrac{\pi_{ij}}{1-\pi_{ij}}\right)=\beta_0+Center_{ij}\beta_1+Treat_i\beta_2+Age_i\beta_3+Sex_i\beta_4+Baseline_i\beta_5
\]</span></p>
<section id="qic-quasi-information-criterion-for-model-selection" class="level4">
<h4 class="anchored" data-anchor-id="qic-quasi-information-criterion-for-model-selection">QIC (Quasi Information Criterion) for Model Selection**</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Displays table of QIC between all 4 different types of GEE models with different</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># correlation structure</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">QIC</span>(gee_independence, gee_exchangeable, gee_unstructured, gee_ar1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 QIC QICu Quasi Lik  CIC params QICC
gee_independence 513  499      -244 12.5      6  514
gee_exchangeable 513  499      -244 12.5      6  515
gee_unstructured 512  500      -244 12.4      6  520
gee_ar1          513  500      -244 12.7      6  516</code></pre>
</div>
</div>
<p>In order to evaluate which correlation structure is best to use with GEE models, QIC, quasilikelihood information criterion, must be used instead of the AIC, Akaike’s information criterion, to assess since GEE is not based on a specified distribution. AIC uses the asymptotic nature of the maximum likelihood estimator for a specified distribution and is therefore not applicable for GEE. <span class="citation" data-cites="pan2001akaike">(<a href="#ref-pan2001akaike" role="doc-biblioref">Pan 2001</a>)</span> When comparing the different correlation structures used for GEE, the smallest QIC value is the indicator for which is the best correlation structure to use. For the respiratory dataset, the unstructured correlation structure has the lowest QIC value of 512 when compared to the other correlation structures.Therefore, use of the unstructured correlation structure should be used for the GEE model for the respiratory dataset.</p>
</section>
</section>
<section id="inference" class="level3">
<h3 class="anchored" data-anchor-id="inference">Inference</h3>
<p>GEE provides robust standard errors for the estimated regression parameters, taking into account the correlation structure. When comparing multiple different techniques, it’s important to consider the correlation between observations in order to perform accurate statistical inference of the model’s output. <span class="citation" data-cites="seals2016analysis">(<a href="#ref-seals2016analysis" role="doc-biblioref">Seals and Aban 2016</a>)</span> Hypothesis tests and confidence intervals can be constructed to assess the statistical significance of the variables and make inferences about the population-level effects. <span class="citation" data-cites="shao2023comparison">(<a href="#ref-shao2023comparison" role="doc-biblioref">Shao et al. 2023</a>)</span></p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>GEE is a valid choice of statistical modeling to be used in cases when assumptions for linear regression models and generalized linear models do not hold such as datasets with non-normal data, dependence in observations, longitudinal or panel data, clustered or correlated data. In addition, when there are large amounts of higher dimensional data and finding the likelihood functions is very difficult computationally, GEE provides an easy alternative and gives stable, consistent estimates for parameters without the need for the possibly intense likelihood calculations. GEE can be used for continuous, binary or count responses.</p>
<p>Analyzing longitudinal datasets with repeated observations is one of the biggest applications for GEE and it is used extensively in studies in the sciences and health services. If a GEE model is not used in these cases and the between-observation correlation is ignored, then there may be an incorrect conclusion of significant results, or type I errors. <span class="citation" data-cites="seals2016analysis">(<a href="#ref-seals2016analysis" role="doc-biblioref">Seals and Aban 2016</a>)</span> GEE handles the correlation by using defined correlation structures as part of its process to find parameter estimates and even if the correlation structure chosen is not correct, the estimates are still consistent although standard errors may be not correct which is a potential drawback of the method.</p>
<p>The ‘geepack’ package in R was used to calculated GEE models to analyze a longitudinal respiratory dataset that exhibited correlation between individual patient observations. All (4) available correlation structures were used to determine which structure would yield the best GEE model and based on QIC, the unstructured correlation structure was the best. There are a few other packages available in R to create GEE models not discussed in this review GEE. They are the ‘gee’ package <span class="citation" data-cites="Carey2022">(<a href="#ref-Carey2022" role="doc-biblioref">V 2022</a>)</span> and ‘multgee’ pagkage specifically for multinomial responses <span class="citation" data-cites="touloumis2014r">(<a href="#ref-touloumis2014r" role="doc-biblioref">Touloumis 2014</a>)</span>.</p>
<p>GEE uses quasilikelihood estimation which is opposite of other models that use maximum likelihood estimation or the least squares methods. <span class="citation" data-cites="shao2023comparison">(<a href="#ref-shao2023comparison" role="doc-biblioref">Shao et al. 2023</a>)</span> To summarize, GEE is a good extension of GLM for modeling longitudinal or panel data and data with binary or continuous outcomes. The fact that the individual observations do not have to be independent or a distribution specified combined with the fact that the models are based on the first moment only and use of one several possible correlation structures make it a good choice for modeling.</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<section id="literature-review" class="level3">
<h3 class="anchored" data-anchor-id="literature-review">Literature Review</h3>
<p><a href="https://docs.google.com/document/d/1h3yuMl3h2s_q4uzmoouksLEmx3fMcz9ML1uDiyCilMI/edit?usp=sharing">Generalized Estimating Equations Literature Review</a></p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-agresti2015foundations" class="csl-entry" role="listitem">
Agresti, Alan. 2015. <em>Foundations of Linear and Generalized Linear Models</em>. John Wiley &amp; Sons.
</div>
<div id="ref-barnhart1998goodness" class="csl-entry" role="listitem">
Barnhart, Huiman X, and John M Williamson. 1998. <span>“Goodness-of-Fit Tests for GEE Modeling with Binary Responses.”</span> <em>Biometrics</em>, 720–29.
</div>
<div id="ref-Burton1998" class="csl-entry" role="listitem">
Burton, Lyle Gurrin, Paul, and Peter Sly. 1998. <span>“Extending the Simple Linear Regression Model to Account for Correlated Responses: An Introduction to Generalized Estimating Equations and Multi-Level Mixed Modelling.”</span> <em>Statistics in Medicine</em> 17 (11): 1261–91. <a href="https://doi.org/10.1002/(SICI)1097-0258(19980615)17:11<1261::AID-SIM846>3.0.CO;2-Z">https://doi.org/10.1002/(SICI)1097-0258(19980615)17:11&lt;1261::AID-SIM846&gt;3.0.CO;2-Z</a>.
</div>
<div id="ref-crespi2009using" class="csl-entry" role="listitem">
Crespi, Catherine M, Weng Kee Wong, and Shiraz I Mishra. 2009. <span>“Using Second-Order Generalized Estimating Equations to Model Heterogeneous Intraclass Correlation in Cluster-Randomized Trials.”</span> <em>Statistics in Medicine</em> 28 (5): 814–27.
</div>
<div id="ref-d2011generalized" class="csl-entry" role="listitem">
D’Angelo, Gina M, Nicole A Lazar, William F Eddy, John C Morris, and Yvette I Sheline. 2011. <span>“A Generalized Estimating Equations Approach for Resting-State Functional MRI Group Analysis.”</span> In <em>2011 Annual International Conference of the IEEE Engineering in Medicine and Biology Society</em>, 5064–67. IEEE.
</div>
<div id="ref-donald2006longitudinal" class="csl-entry" role="listitem">
Donald, Hedeker, and D Gibbons Robert. 2006. <span>“Longitudinal Data Analysis.”</span> <em>John Wiley &amp; Sons, Inc., Hoboken, NJ. DOI</em> 10: 0470036486.
</div>
<div id="ref-garson2013generalized" class="csl-entry" role="listitem">
Garson, GD. 2013. <span>“Generalized Linear Models/Generalized Estimating Equations. 2013 Ed.”</span> <em>Asheboro, NC: Statistical Associates Publishers</em>.
</div>
<div id="ref-gayen2018generalized" class="csl-entry" role="listitem">
Gayen, Atin, and M Ashok Kumar. 2018. <span>“Generalized Estimating Equation for the Student-t Distributions.”</span> In <em>2018 IEEE International Symposium on Information Theory (ISIT)</em>, 571–75. IEEE.
</div>
<div id="ref-Hojsgaard2006" class="csl-entry" role="listitem">
Halekoh, Ulrich, Søren Højsgaard, and Jun Yan. 2006. <span>“The r Package Geepack for Generalized Estimating Equations.”</span> <em>Journal of Statistical Software</em> 15/2: 1–11.
</div>
<div id="ref-hanley2003statistical" class="csl-entry" role="listitem">
Hanley, James A, Abdissa Negassa, Michael D deB Edwardes, and Janet E Forrester. 2003. <span>“Statistical Analysis of Correlated Data Using Generalized Estimating Equations: An Orientation.”</span> <em>American Journal of Epidemiology</em> 157 (4): 364–75.
</div>
<div id="ref-hardin2013generalized" class="csl-entry" role="listitem">
Hardin, J, and J Hilbe. 2013. <span>“Generalized Estimating Equations (Second.).”</span> New York: CRC Press.
</div>
<div id="ref-hin2009working" class="csl-entry" role="listitem">
Hin, Lin-Yee, and You-Gan Wang. 2009. <span>“Working-Correlation-Structure Identification in Generalized Estimating Equations.”</span> <em>Statistics in Medicine</em> 28 (4): 642–58.
</div>
<div id="ref-homish2010analyzing" class="csl-entry" role="listitem">
Homish, Gregory G, Ellen P Edwards, Rina D Eiden, and Kenneth E Leonard. 2010. <span>“Analyzing Family Data: A GEE Approach for Substance Use Researchers.”</span> <em>Addictive Behaviors</em> 35 (6): 558–63.
</div>
<div id="ref-Huang2022" class="csl-entry" role="listitem">
Huang, Francis L. 2022. <span>“Analyzing Cross-Sectionally Clustered Data Using Generalized Estimating Equations.”</span> <em>Journal of Educational and Behavioral Statistics</em> 47 (1): 101–25. <a href="https://doi.org/10.3102/10769986211017480">https://doi.org/10.3102/10769986211017480</a>.
</div>
<div id="ref-hubbard2010gee" class="csl-entry" role="listitem">
Hubbard, Alan E, Jennifer Ahern, Nancy L Fleischer, Mark Van der Laan, Sheri A Satariano, Nicholas Jewell, Tim Bruckner, and William A Satariano. 2010. <span>“To GEE or Not to GEE: Comparing Population Average and Mixed Models for Estimating the Associations Between Neighborhood Risk Factors and Health.”</span> <em>Epidemiology</em>, 467–74.
</div>
<div id="ref-huh2012optimizing" class="csl-entry" role="listitem">
Huh, David, Brian P Flaherty, and Jane M Simoni. 2012. <span>“Optimizing the Analysis of Adherence Interventions Using Logistic Generalized Estimating Equations.”</span> <em>AIDS and Behavior</em> 16: 422–31.
</div>
<div id="ref-ito2022grouped" class="csl-entry" role="listitem">
Ito, Tsubasa, and Shonosuke Sugasawa. 2022. <span>“Grouped Generalized Estimating Equations for Longitudinal Data Analysis.”</span> <em>Biometrics</em>.
</div>
<div id="ref-koch1990categorical" class="csl-entry" role="listitem">
Koch, Gary G, Gregory J Carr, Ingrid A Amara, Maura E Stokes, and Thomas J Uryniak. 1990. <span>“Categorical Data Analysis.”</span> <em>Statistical Methodology in the Pharmaceutical Sciences</em> 13: 389–470.
</div>
<div id="ref-koper2009generalized" class="csl-entry" role="listitem">
Koper, Nicola, and Micheline Manseau. 2009. <span>“Generalized Estimating Equations and Generalized Linear Mixed-Effects Models for Modelling Resource Selection.”</span> <em>Journal of Applied Ecology</em>, 590–99.
</div>
<div id="ref-Liang1986longitudinal" class="csl-entry" role="listitem">
Liang, Kung-Yee, and Scott L Zeger. 1986. <span>“Longitudinal Data Analysis Using Generalized Linear Models.”</span> <em>Biometrika</em> 73 (1): 13–22.
</div>
<div id="ref-lin2011impact" class="csl-entry" role="listitem">
Lin, Meng-Lung, and Cheng-Hwang Perng. 2011. <span>“The Impact of Terrain on NDVI Dynamics of Corn Field Using Generalized Estimating Equations and Time-Series MODIS Images.”</span> In <em>2011 IEEE International Geoscience and Remote Sensing Symposium</em>, 3342–45. IEEE.
</div>
<div id="ref-luo2022conditional" class="csl-entry" role="listitem">
Luo, Renwen, and Jianxin Pan. 2022. <span>“Conditional Generalized Estimating Equations of Mean-Variance-Correlation for Clustered Data.”</span> <em>Computational Statistics &amp; Data Analysis</em> 168: 107386.
</div>
<div id="ref-mcculloch1996introduction" class="csl-entry" role="listitem">
McCulloch, Charles E. 1996. <span>“An Introduction to Generalized Linear Mixed Models.”</span>
</div>
<div id="ref-Mcculloch2008" class="csl-entry" role="listitem">
McCulloch, Searle, C. 2008. <em>Generalized, Linear, and Mixed Models, 2nd Edition</em>. Wiley Series in Probability and Statistics. Wiley New Jersey. <a href="https://www.wiley.com/en-us/Generalized%2C+Linear%2C+and+Mixed+Models%2C+2nd+Edition-p-9780470073711">https://www.wiley.com/en-us/Generalized%2C+Linear%2C+and+Mixed+Models%2C+2nd+Edition-p-9780470073711</a>.
</div>
<div id="ref-mcdaniel2013fast" class="csl-entry" role="listitem">
McDaniel, Lee S, Nicholas C Henderson, and Paul J Rathouz. 2013. <span>“Fast Pure r Implementation of GEE: Application of the Matrix Package.”</span> <em>The R Journal</em> 5 (1): 181.
</div>
<div id="ref-nam2017factors" class="csl-entry" role="listitem">
Nam, Ju-Hyun, Myeong-Seob Lim, Hyun-Kyeong Choi, Jae-Yeop Kim, Sung-Kyeong Kim, Sung-Soo Oh, Sang-Baek Koh, and Hee-Tae Kang. 2017. <span>“Factors Increasing the Risk for Psychosocial Stress Among Korean Adults Living in Rural Areas: Using Generalized Estimating Equations and Mixed Models.”</span> <em>Annals of Occupational and Environmental Medicine</em> 29: 1–12.
</div>
<div id="ref-overall2004robustness" class="csl-entry" role="listitem">
Overall, John E, and Scott Tonidandel. 2004. <span>“Robustness of Generalized Estimating Equation (GEE) Tests of Significance Against Misspecification of the Error Structure Model.”</span> <em>Biometrical Journal: Journal of Mathematical Methods in Biosciences</em> 46 (2): 203–13.
</div>
<div id="ref-paik1988repeated" class="csl-entry" role="listitem">
Paik, Myunghee C. 1988. <span>“Repeated Measurement Analysis for Nonnormal Data in Small Samples.”</span> <em>Communications in Statistics-Simulation and Computation</em> 17 (4): 1155–71.
</div>
<div id="ref-pan2001akaike" class="csl-entry" role="listitem">
Pan, Wei. 2001. <span>“Akaike’s Information Criterion in Generalized Estimating Equations.”</span> <em>Biometrics</em> 57 (1): 120–25.
</div>
<div id="ref-paradis2002analysis" class="csl-entry" role="listitem">
Paradis, Emmanuel, and Julien Claude. 2002. <span>“Analysis of Comparative Data Using Generalized Estimating Equations.”</span> <em>Journal of Theoretical Biology</em> 218 (2): 175–85.
</div>
<div id="ref-pekar2018generalized" class="csl-entry" role="listitem">
Pekár, Stano, and Marek Brabec. 2018. <span>“Generalized Estimating Equations: A Pragmatic and Flexible Approach to the Marginal GLM Modelling of Correlated Data in the Behavioural Sciences.”</span> <em>Ethology</em> 124 (2): 86–93.
</div>
<div id="ref-salazar2016simple" class="csl-entry" role="listitem">
Salazar, Alejandro, Begoña Ojeda, Marı́a Dueñas, Fernando Fernández, and Inmaculada Failde. 2016. <span>“Simple Generalized Estimating Equations (GEEs) and Weighted Generalized Estimating Equations (WGEEs) in Longitudinal Studies with Dropouts: Guidelines and Implementation in r.”</span> <em>Statistics in Medicine</em> 35 (19): 3424–48.
</div>
<div id="ref-Schwartz2023" class="csl-entry" role="listitem">
Schwartz S, Barrett T. 2023. <span>“Encyclopedia of Quantitative Methods in r, Vol 5, 15-19: GEE.”</span> 2023. <a href="https://cehs-research.github.io/eBook_multilevel/gee-binary-outcome-respiratory-illness.html">https://cehs-research.github.io/eBook_multilevel/gee-binary-outcome-respiratory-illness.html</a>.
</div>
<div id="ref-seals2016analysis" class="csl-entry" role="listitem">
Seals, Samantha R, and Inmaculada B Aban. 2016. <span>“Analysis of the 17-Segment Left Ventricle Model Using Generalized Estimating Equations.”</span> <em>Journal of Nuclear Cardiology</em>. Springer.
</div>
<div id="ref-sepato2014generalized" class="csl-entry" role="listitem">
Sepato, Sandra Moepeng. 2014. <span>“Generalized Linear Mixed Model and Generalized Estimating Equation for Binary Longitudinal Data.”</span> PhD thesis, University of Pretoria.
</div>
<div id="ref-shao2023comparison" class="csl-entry" role="listitem">
Shao, Sijing, Judith E Canner, Rebecca A Everett, Kidist Bekele-Maxwell, Alexis Kuerbis, Lyric Stephenson, Jennifer Menda, Jon Morgenstern, and HT Banks. 2023. <span>“A Comparison of Mathematical and Statistical Modeling with Longitudinal Data: An Application to Ecological Momentary Assessment of Behavior Change in Individuals with Alcohol Use Disorder.”</span> <em>Bulletin of Mathematical Biology</em> 85 (1): 5.
</div>
<div id="ref-PSU2023" class="csl-entry" role="listitem">
Statistics, Penn State Department of. 2023. <span>“Analysis of Discrete Data, 12: Advanced Topics II.”</span> 2023. <a href="https://online.stat.psu.edu/stat504/lesson/12/12.2">https://online.stat.psu.edu/stat504/lesson/12/12.2</a>.
</div>
<div id="ref-touloumis2014r" class="csl-entry" role="listitem">
Touloumis, Anestis. 2014. <span>“R Package Multgee: A Generalized Estimating Equations Solver for Multinomial Responses.”</span> <em>arXiv Preprint arXiv:1410.5232</em>.
</div>
<div id="ref-Carey2022" class="csl-entry" role="listitem">
V, Carey. 2022. <span>“Gee: Generalized Estimation Equation Solver.”</span> 2022. <a href="https://cran.r-project.org/package=gee">https://cran.r-project.org/package=gee</a>.
</div>
<div id="ref-wang2012penalized" class="csl-entry" role="listitem">
Wang, Lan, Jianhui Zhou, and Annie Qu. 2012. <span>“Penalized Generalized Estimating Equations for High-Dimensional Longitudinal Data Analysis.”</span> <em>Biometrics</em> 68 (2): 353–60.
</div>
<div id="ref-wang2014generalized" class="csl-entry" role="listitem">
Wang, Ming. 2014. <span>“Generalized Estimating Equations in Longitudinal Data Analysis: A Review and Recent Developments.”</span> <em>Advances in Statistics</em> 2014.
</div>
<div id="ref-warton2011regularized" class="csl-entry" role="listitem">
Warton, David I. 2011. <span>“Regularized Sandwich Estimators for Analysis of High-Dimensional Data Using Generalized Estimating Equations.”</span> <em>Biometrics</em> 67 (1): 116–23.
</div>
<div id="ref-Yan2002" class="csl-entry" role="listitem">
Yan, Jun. 2002. <span>“Geepack: Yet Another Package for Generalized Estimating Equations.”</span> <em>R-News</em> 2/3: 12–14.
</div>
<div id="ref-Yan2004" class="csl-entry" role="listitem">
Yan, Jun, and Jason P. Fine. 2004. <span>“Estimating Equations for Association Structures.”</span> <em>Statistics in Medicine</em> 23: 859–80.
</div>
<div id="ref-zeileis2019package" class="csl-entry" role="listitem">
Zeileis, Achim, Thomas Lumley, Susanne Berger, Nathaniel Graham, and Maintainer Achim Zeileis. 2019. <span>“Package <span>‘Sandwich’</span>.”</span> <em>R Package Version</em>, 2–5.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>